### PR TITLE
Add Portuguese translation

### PR DESCRIPTION
**Pull request by nunojeronimo**

### CODE REVIEW

**Comment by m-reka** [comment]
Dear @nunojeronimo,

Thank you very much for your support and your great work!
Unfortunately, we can't accept directly your PR concerning translation on GH. We use the weblate platform for open source translations as explained here: https://www.mailcleaner.org/translations/. Every translation must came from weblate.

We're currently working on a dynamic integration of translations into MailCleaner and will publish it soon. Our team will check every changed that can be integrated from your PR and will inform you here.

Please don't hesitate to transfer your translations directly to weblate as explained on our website. 

Thank you in advance and for your understanding.
Mentor

P.S: we will edit the main README in order to clarify all these things ^^

**Comment by nunojeronimo** [comment]
Hi,
I had already translated all available translation in weblate. I did this translations in git because I didn't see them in weblate. 

PS. Translated the new strings regarding #24

**Comment by Mrngilles** [comment]
Hello,
The new languages translated should now be available for every MailCleaner.
Thank you for your work !
Marin

**Comment by Mrngilles** [comment]
Hi,
Thanks again for your work.
I am closing this ticket to clean up.
Marin

**Pull request closed without merging**
