### PR TITLE
Add interface to manage newsletters

### PR DESCRIPTION
**Pull request by Mrngilles**

### CODE REVIEW

**Comment by enoch85** [comment]
Any screenshot?

**Comment by enoch85** [comment]
Also, does this mean that the administrator can administrate all the users newsletter addresses as well, without the need to login to each separate account?

Would be awesome!

**Comment by enoch85** [comment]
>  If you want to manage for given users, you would still have to go in each of the users account

Would be awesome if you could implement it in the coming versions, would make the administration for ServiceDesks (like in our case) so much easier as we handle all the spam and newsletter requests.

Thanks for the screenshots!

**Comment by Mrngilles** [comment]
I'll add it to our features request then.
Thanks

**Pull request merged**
